version: "3"

services:
  redis-server: 
    image: 'redis'
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5437:5432'
    expose:
      - "5437"
  app:
    depends_on:
      - postgres
    restart: always
    build: .
    environment:
      - PORT=9000
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_PORT=5432
      - DB_HOST=postgres
      - DB_DATABASE=your_db_name
      - REDIS_HOST=redis-server
      - APP_TOKEN_SECRET=tefasfasgehewhweghewjgkwqgoiwgjig2i9gi3gijoadskglasg
      - APP_TOKEN_EXPIRY=30d
      - SYSTEM_EMAIL=
      - SYSTEM_EMAIL_PASSWORD=
      - APP_DOMAIN=http://localhost:9000
      - PUSH_OVER_TOKEN=
      - PUSH_OVER_SUBSCRIBTION_LINK=
    ports:
      - "9000:9000"
